@startuml

!define ICONURL ../lib/1ce-icons-for-plantuml-main/dist
!include ICONURL/common.puml
!include ICONURL/all.puml
!include ICONURL/v8_ScheduledJob.puml
!include ICONURL/v8_InfoRg.puml
!include ICONURL/v8_WebService.puml
!include ICONURL/v8_CommonModule.puml
!include ICONURL/v8_Catalog.puml
!include ICONURL/v8_Document.puml
!include ICONURL/v8_AccRg.puml
!include ICONURL/v8_CalculationRg.puml
!include ICONURL/v8_AccRg.puml

!define _CS scale=1
!define _MS scale=1.5
!define _SS scale=0.5

!define _ScheduledJob <$scheduledjob{_MS}>
!define _InfoRg <$inforg{_MS}>
!define _CalculationRg <$calculationrg{_MS}>
!define _WebService <$webservice{_MS}>
!define _CommonModule <$commonmodule{_MS}>
!define _Catalog <$catalog{_MS}>
!define _Document <$document{_MS}>


'>>> библиотека 1ce-icons-for-plantuml (ext)
!define v8_PUML https://raw.githubusercontent.com/plastinin/1ce-icons-for-plantuml/extended/dist/
!include v8_PUML/common.puml
!include v8_PUML/v8_AccRg.puml
!include v8_PUML/v8_Document.puml
!include v8_PUML/v8_Catalog.puml
!include v8_PUML/v8_InfoRg.puml
!include v8_PUML/v8_ChartsOfCharacteristicTypes.puml
!include v8_PUML/v8_DefinedTypes.puml
!include v8_PUML/v8_Enum.puml
'<<<

package СистемаЛояльностиНаПредприятии <<Rectangle>> #b3c6ff {

_Справочник(Контрагенты, "Контрагенты") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
	 ВидЦен
	 КонтактноеЛицо
	 Телефон
	 ЭлектроннаяПочта
}
_Справочник(КартыЛояльности, "Карты лояльности") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
	 {static} Владелец
	 Штрихкод
	 Статус
	 Контрагент
	 ПроцентСкидки
	 ПроцентНачисляемыхБаллов
}

_Справочник(ВидыКартЛояльности, "Виды карт лояльности") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
	 Статус
	 ДатаНачалаДействия
	 Организация
	 Комментарий
	 АвтоматическиСписыватьБаллы
	 ВидБонуснойПрограммы
	 ПроцентСкидки
	 ПроцентНачисляемыхБаллов
}

_Справочник(Организации, "Организации") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
}

_Справочник(ВидыЦен, "Виды цен") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
}

_Справочник(Валюты, "Валюты") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
}

_Справочник(Склады, "Склады") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
}

_Справочник(Товары, "Товары") {
	 {static} Наименование
	 {static} Код
	 {static} ПометкаУдаления
	 Артикул
	 Вид
	 Описание
	 Поставщик
}

_Документ(ЗаказыТоваров, "Заказы товаров") {
	 {static} Дата
	 {static} Номер
	 {static} ПометкаУдаления
	 {static} Проведен
	 Автор
	 Валюта
	 ВидКартЛояльности
	 ВидЦен
	 Организация
	 Покупатель
	 Склад
	 СостояниеЗаказа
	 СписатьБаллы
	 Сумма
	 ---Товары---
	 Товар
	 Цена
	 Количество
	 Сумма
	 ПроцентСкидки
	 Баллы
}
_Документ(РасходТовара, "Продажа") {
	 {static} Дата
	 {static} Номер
	 {static} ПометкаУдаления
	 {static} Проведен
	 Валюта
	 ВидКартЛояльности
	 ВидЦен
	 ОбоснованиеОтгрузки
	 Организация
	 Покупатель
	 Склад	
	 СписатьБаллы
	---Товары---
	 Товар
	 Цена
	 Количество
	 Сумма
	 ПроцентСкидки
	 Баллы
}

_Документ(ПоступлениеДенег, "Поступление денег") {
	 {static} Дата
	 {static} Номер
	 {static} ПометкаУдаления
	 {static} Проведен
	 Валюта
	 Покупатель
	 Сумма
	 Организация
}

_РегистрСведений(ЦеныТоваров, "Цены товаров") {
	 {static} Период
	 <$d> Товар
	 <$d> ВидЦен
	 <$r> Цена
}
_РегистрНакопления(Взаиморасчеты, "Взаиморасчеты") {
	 {static} Регистратор
	 {static} Период
	 <$d> Контрагент
	 <$d> Валюта
	 <$r> Сумма
	 <$r> Скидка
}

_РегистрНакопления(Продажи, "Продажи") {
	 {static} Регистратор
	 {static} Период
	 <$d> Покупатель
	 <$d> Товар
	 <$r> Количество
	 <$r> Сумма
	 <$r> Скидка
}

_РегистрНакопления(ТоварныеЗапасы, "Товарные запасы") {
	 {static} Регистратор
	 {static} Период
	 <$d> Склад
	 <$d> Товар
	 <$r> Количество
}

_РегистрНакопления(БонусныеБаллы, "Бонусные баллы") {
	 {static} Регистратор
	 {static} Период
	 <$d> ВидКартЛояльности
	 <$d> Партнер
	 <$r> Начислено
	 <$r> КСписанию
}


}


'Связи пропуска
Контрагенты --> ЗаказыТоваров::Покупатель
Контрагенты --> РасходТовара::Покупатель
Контрагенты --> ПоступлениеДенег::Покупатель
Контрагенты --> Товары::Поставщик
Контрагенты --> КартыЛояльности::Контрагент
Контрагенты --> БонусныеБаллы::Партнер
Контрагенты --> Взаиморасчеты::Контрагент
Контрагенты --> Продажи::Покупатель

Организации --> ЗаказыТоваров::Организация
Организации --> РасходТовара::Организация
Организации --> ПоступлениеДенег::Организация
Организации --> ВидыКартЛояльности::Организация

Валюты --> ПоступлениеДенег::Валюта
Валюты --> ЗаказыТоваров::Валюта
Валюты --> РасходТовара::Валюта
Валюты --> Взаиморасчеты::Валюта

ВидыЦен --> ЗаказыТоваров::ВидЦен
ВидыЦен --> РасходТовара::ВидЦен
ВидыЦен --> ЦеныТоваров::ВидЦен

Склады --> ЗаказыТоваров::Склад
Склады --> РасходТовара::Склад
Склады --> ТоварныеЗапасы::Склад

ВидыКартЛояльности --> КартыЛояльности::Владелец
ВидыКартЛояльности --> ЗаказыТоваров::ВидКартЛояльности
ВидыКартЛояльности --> РасходТовара::ВидКартЛояльности
ВидыКартЛояльности --> БонусныеБаллы::ВидКартЛояльности

Товары --> ЦеныТоваров::Товар
Товары --> ЗаказыТоваров::Товар
Товары --> РасходТовара::Товар
Товары --> Продажи::Товар
Товары --> ТоварныеЗапасы::Товар

ЦеныТоваров::Цена --> ЗаказыТоваров::Цена
ЦеныТоваров::Цена --> РасходТовара::Цена

РасходТовара --> Взаиморасчеты::Регистратор
РасходТовара --> Продажи::Регистратор
РасходТовара --> ТоварныеЗапасы::Регистратор
РасходТовара::Товар --> ТоварныеЗапасы::Товар
РасходТовара::Скад --> ТоварныеЗапасы::Скад
РасходТовара --> БонусныеБаллы::Регистратор

ПоступлениеДенег --> Взаиморасчеты::Регистратор
ПоступлениеДенег::Покупатель --> Взаиморасчеты::Контрагент
ПоступлениеДенег::Валюта --> Взаиморасчеты::Валюта

ЗаказыТоваров --> РасходТовара::ОбоснованиеОтгрузки

@enduml